name: Release

on:
  push:
    branches: [master]

permissions: {}

jobs:
  Release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      releases_created: ${{ steps.rp.outputs.releases_created }}
    steps:
      - id: rp
        uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/release-please-config.json
          manifest-file: .release-please-manifest.json

  Publish:
    needs: Release-please
    if: needs.Release-please.outputs.releases_created == 'true'
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/publish.yml
